-- Seed da base FICTICIA do prototipo - Assistente Virtual da Farmacia Municipal
-- Quantitativos simulados. Nao representam estoque real de nenhuma farmacia.

begin;

truncate table public.sinonimos, public.medicamentos, public.unidades restart identity cascade;

insert into public.unidades (id, nome, endereco, horario, telefone) values
  ('UN-01', 'Farmácia Municipal Central', 'Rua das Flores, 100 - Centro', 'Segunda a sexta, 7h às 17h', '(00) 0000-0001'),
  ('UN-02', 'Farmácia da UBS Bairro Novo', 'Av. Principal, 500 - Bairro Novo', 'Segunda a sexta, 7h às 16h', '(00) 0000-0002'),
  ('UN-03', 'Farmácia da UBS Vila Esperança', 'Rua São João, 25 - Vila Esperança', 'Segunda a sexta, 8h às 16h', '(00) 0000-0003');

insert into public.medicamentos (codigo, principio_ativo, apresentacao, forma_farmaceutica, componente, unidade_medida, estoque_atual, estoque_minimo, tipo_receita, unidade_id) values
  ('MED-001', 'Dipirona sódica', '500 mg', 'Comprimido', 'Básico', 'Comprimido', 4820, 800, 'Receita simples', 'UN-01'),
  ('MED-002', 'Dipirona sódica', '500 mg/mL solução oral 10 mL', 'Solução oral', 'Básico', 'Frasco', 0, 60, 'Receita simples', 'UN-01'),
  ('MED-003', 'Paracetamol', '500 mg', 'Comprimido', 'Básico', 'Comprimido', 3150, 700, 'Receita simples', 'UN-01'),
  ('MED-004', 'Paracetamol', '200 mg/mL solução oral 15 mL', 'Solução oral', 'Básico', 'Frasco', 42, 50, 'Receita simples', 'UN-01'),
  ('MED-005', 'Ibuprofeno', '300 mg', 'Comprimido', 'Básico', 'Comprimido', 1240, 400, 'Receita simples', 'UN-01'),
  ('MED-006', 'Amoxicilina', '500 mg', 'Cápsula', 'Básico', 'Cápsula', 2600, 600, 'Receita de antimicrobiano (2 vias)', 'UN-01'),
  ('MED-007', 'Amoxicilina', '50 mg/mL pó para suspensão oral 60 mL', 'Suspensão oral', 'Básico', 'Frasco', 18, 30, 'Receita de antimicrobiano (2 vias)', 'UN-01'),
  ('MED-008', 'Azitromicina', '500 mg', 'Comprimido', 'Básico', 'Comprimido', 0, 200, 'Receita de antimicrobiano (2 vias)', 'UN-01'),
  ('MED-009', 'Cefalexina', '500 mg', 'Cápsula', 'Básico', 'Cápsula', 940, 250, 'Receita de antimicrobiano (2 vias)', 'UN-01'),
  ('MED-010', 'Sulfametoxazol + Trimetoprima', '400 mg + 80 mg', 'Comprimido', 'Básico', 'Comprimido', 1180, 300, 'Receita de antimicrobiano (2 vias)', 'UN-01'),
  ('MED-011', 'Metronidazol', '250 mg', 'Comprimido', 'Básico', 'Comprimido', 760, 200, 'Receita de antimicrobiano (2 vias)', 'UN-01'),
  ('MED-012', 'Fluconazol', '150 mg', 'Cápsula', 'Básico', 'Cápsula', 210, 60, 'Receita simples', 'UN-01'),
  ('MED-013', 'Metformina', '850 mg', 'Comprimido', 'Básico', 'Comprimido', 8600, 1500, 'Receita simples', 'UN-01'),
  ('MED-014', 'Glibenclamida', '5 mg', 'Comprimido', 'Básico', 'Comprimido', 3400, 900, 'Receita simples', 'UN-01'),
  ('MED-015', 'Insulina NPH humana', '100 UI/mL frasco 10 mL', 'Suspensão injetável', 'Básico', 'Frasco', 96, 40, 'Receita simples (rede de frio)', 'UN-01'),
  ('MED-016', 'Insulina regular humana', '100 UI/mL frasco 10 mL', 'Solução injetável', 'Básico', 'Frasco', 31, 25, 'Receita simples (rede de frio)', 'UN-01'),
  ('MED-017', 'Losartana potássica', '50 mg', 'Comprimido', 'Básico', 'Comprimido', 12400, 2000, 'Receita simples', 'UN-01'),
  ('MED-018', 'Enalapril maleato', '10 mg', 'Comprimido', 'Básico', 'Comprimido', 5900, 1200, 'Receita simples', 'UN-01'),
  ('MED-019', 'Captopril', '25 mg', 'Comprimido', 'Básico', 'Comprimido', 2100, 800, 'Receita simples', 'UN-01'),
  ('MED-020', 'Hidroclorotiazida', '25 mg', 'Comprimido', 'Básico', 'Comprimido', 7300, 1200, 'Receita simples', 'UN-01'),
  ('MED-021', 'Anlodipino besilato', '5 mg', 'Comprimido', 'Básico', 'Comprimido', 4100, 900, 'Receita simples', 'UN-01'),
  ('MED-022', 'Atenolol', '50 mg', 'Comprimido', 'Básico', 'Comprimido', 880, 900, 'Receita simples', 'UN-01'),
  ('MED-023', 'Propranolol cloridrato', '40 mg', 'Comprimido', 'Básico', 'Comprimido', 2450, 600, 'Receita simples', 'UN-01'),
  ('MED-024', 'Sinvastatina', '20 mg', 'Comprimido', 'Básico', 'Comprimido', 6800, 1500, 'Receita simples', 'UN-01'),
  ('MED-025', 'Ácido acetilsalicílico', '100 mg', 'Comprimido', 'Básico', 'Comprimido', 9200, 1500, 'Receita simples', 'UN-01'),
  ('MED-026', 'Omeprazol', '20 mg', 'Cápsula', 'Básico', 'Cápsula', 5400, 1000, 'Receita simples', 'UN-01'),
  ('MED-027', 'Metoclopramida cloridrato', '10 mg', 'Comprimido', 'Básico', 'Comprimido', 1320, 300, 'Receita simples', 'UN-01'),
  ('MED-028', 'Prednisona', '20 mg', 'Comprimido', 'Básico', 'Comprimido', 640, 200, 'Receita simples', 'UN-01'),
  ('MED-029', 'Prednisolona fosfato sódico', '3 mg/mL solução oral 60 mL', 'Solução oral', 'Básico', 'Frasco', 0, 40, 'Receita simples', 'UN-01'),
  ('MED-030', 'Dexametasona', '0,1% creme 10 g', 'Creme dermatológico', 'Básico', 'Bisnaga', 155, 40, 'Receita simples', 'UN-01'),
  ('MED-031', 'Loratadina', '10 mg', 'Comprimido', 'Básico', 'Comprimido', 2900, 500, 'Receita simples', 'UN-01'),
  ('MED-032', 'Salbutamol sulfato', '100 mcg/dose aerossol', 'Aerossol oral', 'Básico', 'Frasco', 74, 60, 'Receita simples', 'UN-01'),
  ('MED-033', 'Beclometasona dipropionato', '250 mcg/dose aerossol', 'Aerossol oral', 'Básico', 'Frasco', 58, 30, 'Receita simples', 'UN-01'),
  ('MED-034', 'Albendazol', '400 mg', 'Comprimido mastigável', 'Básico', 'Comprimido', 1450, 300, 'Receita simples', 'UN-01'),
  ('MED-035', 'Ivermectina', '6 mg', 'Comprimido', 'Básico', 'Comprimido', 0, 150, 'Receita simples', 'UN-01'),
  ('MED-036', 'Levotiroxina sódica', '50 mcg', 'Comprimido', 'Básico', 'Comprimido', 6100, 1200, 'Receita simples', 'UN-01'),
  ('MED-037', 'Sulfato ferroso', '40 mg de ferro elementar', 'Comprimido', 'Básico', 'Comprimido', 8800, 1500, 'Receita simples', 'UN-01'),
  ('MED-038', 'Ácido fólico', '5 mg', 'Comprimido', 'Básico', 'Comprimido', 5200, 1000, 'Receita simples', 'UN-01'),
  ('MED-039', 'Sais para reidratação oral', 'envelope 27,9 g', 'Pó para solução oral', 'Estratégico', 'Envelope', 620, 200, 'Não exige receita', 'UN-01'),
  ('MED-040', 'Nistatina', '100.000 UI/mL suspensão oral 50 mL', 'Suspensão oral', 'Básico', 'Frasco', 27, 30, 'Receita simples', 'UN-01'),
  ('MED-041', 'Permetrina', '5% loção 60 mL', 'Loção', 'Básico', 'Frasco', 88, 30, 'Receita simples', 'UN-01'),
  ('MED-042', 'Etinilestradiol + Levonorgestrel', '0,03 mg + 0,15 mg', 'Comprimido', 'Básico', 'Cartela', 430, 120, 'Receita simples', 'UN-01'),
  ('MED-043', 'Amitriptilina cloridrato', '25 mg', 'Comprimido', 'Básico', 'Comprimido', 2200, 500, 'Receita de controle especial (C1)', 'UN-01'),
  ('MED-044', 'Fluoxetina cloridrato', '20 mg', 'Cápsula', 'Básico', 'Cápsula', 3600, 800, 'Receita de controle especial (C1)', 'UN-01'),
  ('MED-045', 'Carbamazepina', '200 mg', 'Comprimido', 'Básico', 'Comprimido', 1900, 500, 'Receita de controle especial (C1)', 'UN-01'),
  ('MED-046', 'Clonazepam', '2 mg', 'Comprimido', 'Básico', 'Comprimido', 340, 400, 'Notificação de receita B (azul)', 'UN-01'),
  ('MED-047', 'Diazepam', '5 mg', 'Comprimido', 'Básico', 'Comprimido', 0, 300, 'Notificação de receita B (azul)', 'UN-01'),
  ('MED-048', 'Fenitoína sódica', '100 mg', 'Comprimido', 'Básico', 'Comprimido', 1100, 300, 'Receita de controle especial (C1)', 'UN-01');

insert into public.sinonimos (codigo, termo, termo_norm) values
  ('MED-001', 'dipirona', 'dipirona'),
  ('MED-001', 'novalgina', 'novalgina'),
  ('MED-001', 'anador', 'anador'),
  ('MED-001', 'dipirona sodica', 'dipirona sodica'),
  ('MED-001', 'dipirona comprimido', 'dipirona comprimido'),
  ('MED-001', 'dipirona 500', 'dipirona 500'),
  ('MED-002', 'dipirona gotas', 'dipirona gotas'),
  ('MED-002', 'novalgina gotas', 'novalgina gotas'),
  ('MED-002', 'dipirona liquida', 'dipirona liquida'),
  ('MED-002', 'dipirona crianca', 'dipirona crianca'),
  ('MED-002', 'dipirona infantil', 'dipirona infantil'),
  ('MED-002', 'dipirona bebe', 'dipirona bebe'),
  ('MED-003', 'paracetamol', 'paracetamol'),
  ('MED-003', 'tylenol', 'tylenol'),
  ('MED-003', 'paracetamol 500', 'paracetamol 500'),
  ('MED-004', 'paracetamol gotas', 'paracetamol gotas'),
  ('MED-004', 'tylenol bebe', 'tylenol bebe'),
  ('MED-005', 'ibuprofeno', 'ibuprofeno'),
  ('MED-005', 'alivium', 'alivium'),
  ('MED-005', 'advil', 'advil'),
  ('MED-005', 'ibuprofeno 300', 'ibuprofeno 300'),
  ('MED-006', 'amoxicilina', 'amoxicilina'),
  ('MED-006', 'amoxilina', 'amoxilina'),
  ('MED-006', 'amoxil', 'amoxil'),
  ('MED-007', 'amoxicilina suspensao', 'amoxicilina suspensao'),
  ('MED-007', 'amoxicilina infantil', 'amoxicilina infantil'),
  ('MED-007', 'amoxicilina xarope', 'amoxicilina xarope'),
  ('MED-008', 'azitromicina', 'azitromicina'),
  ('MED-008', 'zitromax', 'zitromax'),
  ('MED-008', 'azitromicina 500', 'azitromicina 500'),
  ('MED-009', 'cefalexina', 'cefalexina'),
  ('MED-009', 'keflex', 'keflex'),
  ('MED-010', 'bactrim', 'bactrim'),
  ('MED-010', 'sulfametoxazol', 'sulfametoxazol'),
  ('MED-010', 'sulfa', 'sulfa'),
  ('MED-010', 'smz tmp', 'smz tmp'),
  ('MED-011', 'metronidazol', 'metronidazol'),
  ('MED-011', 'flagyl', 'flagyl'),
  ('MED-012', 'fluconazol', 'fluconazol'),
  ('MED-012', 'zoltec', 'zoltec'),
  ('MED-013', 'metformina', 'metformina'),
  ('MED-013', 'glifage', 'glifage'),
  ('MED-013', 'metiformina', 'metiformina'),
  ('MED-013', 'remedio de diabetes', 'remedio de diabetes'),
  ('MED-014', 'glibenclamida', 'glibenclamida'),
  ('MED-014', 'daonil', 'daonil'),
  ('MED-015', 'insulina nph', 'insulina nph'),
  ('MED-015', 'insulina', 'insulina'),
  ('MED-015', 'insulina lenta', 'insulina lenta'),
  ('MED-016', 'insulina regular', 'insulina regular'),
  ('MED-016', 'insulina rapida', 'insulina rapida'),
  ('MED-017', 'losartana', 'losartana'),
  ('MED-017', 'losartan', 'losartan'),
  ('MED-017', 'losartana 50', 'losartana 50'),
  ('MED-017', 'remedio de pressao', 'remedio de pressao'),
  ('MED-018', 'enalapril', 'enalapril'),
  ('MED-018', 'renitec', 'renitec'),
  ('MED-019', 'captopril', 'captopril'),
  ('MED-019', 'capoten', 'capoten'),
  ('MED-020', 'hidroclorotiazida', 'hidroclorotiazida'),
  ('MED-020', 'clorana', 'clorana'),
  ('MED-020', 'hidroclorotiazida 25', 'hidroclorotiazida 25'),
  ('MED-021', 'anlodipino', 'anlodipino'),
  ('MED-021', 'amlodipina', 'amlodipina'),
  ('MED-021', 'norvasc', 'norvasc'),
  ('MED-022', 'atenolol', 'atenolol'),
  ('MED-022', 'atenol', 'atenol'),
  ('MED-023', 'propranolol', 'propranolol'),
  ('MED-023', 'inderal', 'inderal'),
  ('MED-024', 'sinvastatina', 'sinvastatina'),
  ('MED-024', 'simvastatina', 'simvastatina'),
  ('MED-024', 'remedio de colesterol', 'remedio de colesterol'),
  ('MED-025', 'aas', 'aas'),
  ('MED-025', 'aspirina', 'aspirina'),
  ('MED-025', 'acido acetilsalicilico', 'acido acetilsalicilico'),
  ('MED-025', 'aas infantil', 'aas infantil'),
  ('MED-026', 'omeprazol', 'omeprazol'),
  ('MED-026', 'omeprasol', 'omeprasol'),
  ('MED-026', 'remedio de gastrite', 'remedio de gastrite'),
  ('MED-027', 'metoclopramida', 'metoclopramida'),
  ('MED-027', 'plasil', 'plasil'),
  ('MED-028', 'prednisona', 'prednisona'),
  ('MED-028', 'meticorten', 'meticorten'),
  ('MED-029', 'prednisolona', 'prednisolona'),
  ('MED-029', 'predsim', 'predsim'),
  ('MED-029', 'corticoide infantil', 'corticoide infantil'),
  ('MED-030', 'dexametasona creme', 'dexametasona creme'),
  ('MED-030', 'pomada de dexametasona', 'pomada de dexametasona'),
  ('MED-031', 'loratadina', 'loratadina'),
  ('MED-031', 'claritin', 'claritin'),
  ('MED-031', 'remedio de alergia', 'remedio de alergia'),
  ('MED-032', 'salbutamol', 'salbutamol'),
  ('MED-032', 'aerolin', 'aerolin'),
  ('MED-032', 'bombinha', 'bombinha'),
  ('MED-033', 'beclometasona', 'beclometasona'),
  ('MED-033', 'clenil', 'clenil'),
  ('MED-034', 'albendazol', 'albendazol'),
  ('MED-034', 'zentel', 'zentel'),
  ('MED-034', 'remedio de verme', 'remedio de verme'),
  ('MED-035', 'ivermectina', 'ivermectina'),
  ('MED-035', 'revectina', 'revectina'),
  ('MED-036', 'levotiroxina', 'levotiroxina'),
  ('MED-036', 'puran t4', 'puran t4'),
  ('MED-036', 'euthyrox', 'euthyrox'),
  ('MED-036', 'remedio de tireoide', 'remedio de tireoide'),
  ('MED-037', 'sulfato ferroso', 'sulfato ferroso'),
  ('MED-037', 'ferro', 'ferro'),
  ('MED-037', 'remedio de anemia', 'remedio de anemia'),
  ('MED-038', 'acido folico', 'acido folico'),
  ('MED-038', 'folico', 'folico'),
  ('MED-039', 'soro de reidratacao', 'soro de reidratacao'),
  ('MED-039', 'sro', 'sro'),
  ('MED-039', 'sal de reidratacao', 'sal de reidratacao'),
  ('MED-040', 'nistatina', 'nistatina'),
  ('MED-040', 'micostatin', 'micostatin'),
  ('MED-041', 'permetrina', 'permetrina'),
  ('MED-041', 'remedio de piolho', 'remedio de piolho'),
  ('MED-041', 'nedax', 'nedax'),
  ('MED-042', 'anticoncepcional', 'anticoncepcional'),
  ('MED-042', 'ciclo 21', 'ciclo 21'),
  ('MED-042', 'microvlar', 'microvlar'),
  ('MED-042', 'pilula', 'pilula'),
  ('MED-043', 'amitriptilina', 'amitriptilina'),
  ('MED-043', 'amytril', 'amytril'),
  ('MED-044', 'fluoxetina', 'fluoxetina'),
  ('MED-044', 'prozac', 'prozac'),
  ('MED-045', 'carbamazepina', 'carbamazepina'),
  ('MED-045', 'tegretol', 'tegretol'),
  ('MED-046', 'clonazepam', 'clonazepam'),
  ('MED-046', 'rivotril', 'rivotril'),
  ('MED-047', 'diazepam', 'diazepam'),
  ('MED-047', 'valium', 'valium'),
  ('MED-048', 'fenitoina', 'fenitoina'),
  ('MED-048', 'hidantal', 'hidantal')
on conflict (codigo, termo_norm) do nothing;

commit;